### ISSUE TITLE
RGI7a freeze roadmap

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#56]
This is a list of outstanding issues for RGI7 ordered by importance in order to prioritize the work over the next few weeks:

### GLIMS internals: required

- [ ] https://github.com/GLIMS-RGI/rgi7_scripts/issues/53
- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/54

### GLIMS ingest: required

- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/3 
- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/26 
- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/52 

### Mapping

- [x]  https://github.com/GLIMS-RGI/rgi7_scripts/issues/55 : Chile / Argentina inventories

### GLIMS ingest: low hanging fruits (not showstoppers but nice to have)

Small updates listed for the [7.0 milestone](https://github.com/GLIMS-RGI/rgi7_scripts/milestone/1): 

- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/4
- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/40
- [x] https://github.com/GLIMS-RGI/rgi7_scripts/issues/60

**Comment by fmaussion** [comment]
RGI7a is published. 7b out to review now
