### ISSUE TITLE
RGI19: workplan georeferencing issues

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#64]
After a short call with prominent glaciologists @iamdonovan  @bruceraup @eberthie @tbolch @willkochtitzky is was decided that:
- the problem outlined in https://github.com/GLIMS-RGI/rgi7_scripts/issues/61 is serious enough to warrant some last minute work to get outline corrections into RGI7
- "80% is better than 100%": shifting the outlines might be enough and much easier than mapping new outlines.
- @willkochtitzky will spend the next couple of weeks assessing what can be done (0%, 80% or 100%) based on Landsat imagery
- we will organize ourselves and avoid double work via this github issue.

Here are some links to get everyone started:
- RGI subregions (helpful to coordinate work) can be downloaded [here](https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l0_RGIv6/00_rgi60_regions.zip)
- GLIMS data (all outlines) for region 19 can be downloaded [here](https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l2_sel_reg_tars/RGI19.tar.gz)
- the subset of GLIMS currently selected for RGI7 (mostly RGI6 [except for Kerguelen](https://github.com/GLIMS-RGI/rgi7_scripts/wiki/RGI19-(Antarctic-and-Subantarctic))) for region 19 can be downloaded [here](https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l3_rgi7a_tar/RGI19.tar.gz)

Based on [topography product coverage](https://rgitools.readthedocs.io/en/latest/dems_subregions.html#rgi19) and manual checks, **here are the subregions which would be best to tackle in order** (providing updated outlines for an entire subregion at once would be best): 

- [ ] 19-05: Balleny Islands | 15 outlines | outlines date 1961
- [ ] 19-01: Subantarctic (Pacific) | 27 outlines | outlines date 1987
- [ ] 19-17: Pine Island Bay 7G | 109 outlines | outlines date 1956
- [ ] 19-02: South Shetlands and South Orkney | 412 outlines (most of which look OK - one island is off) | outlines date 1957
- [ ] 19-03: Subantarctic (Atlantic) | 553 outlines (most of which look OK - only the islands are off) | outlines date 2003 (islands are from 1964)

The west antarctic subregions have few glaciers that seem only slightly shifted: 

- [ ]  19-11: E Queen Maud Land 7A | 162 outlines | outlines date 1956
- [ ] 19-12: Amery Ice Shelf 7B | 1 outlines | outlines date 1956
- [ ] 19-13: Wilkes Land 7C | 73 outlines | outlines date 1956
- [ ] 19-14: Victoria Land 7D | 70 outlines | outlines date 2000
- [ ] 19-24: W Queen Maud Land 7K | 14 outlines | outlines date 1987

And then all the other ones of course :laughing:

**Looking at the list above, it looks like the outline date is a strong indicator that there will be issues with georeferencing.**

**Comment by willkochtitzky** [comment]
Hi all,

Many thanks again for all of your comments last week at our meeting. Especially massive thanks to @fmaussion for so clearly articulating the problem and facilitating these efforts. My students and I have gone through and examined each of the regions above that Fabien has listed. We looked at a combination of Landsat imagery and base layers from ESRI and Google. Below we document the main problems in each region. 

Our solution and path forward:
I will work with my students to completely redraw/fix the following regions:
**19-05: Balleny Islands
19-01: Subantarctic (Pacific)
19-17: Pine Island Bay 7G
19-02: South Shetlands and South Orkney**

*We will complete these outlines and send them to Bruce by the end of September.

For **19-03: Subantarctic (Atlantic)** we already have a proposed solution:
The outlines currently being used for this region as the subset of GLIMS currently selected for RGI7 is wrong. They are from University of Colorado. But instead if we use the outlines submitted by IANIGLA then they will be all correct without issues. This is true for the entire sub-region. 
Below is an example of the UColorado outlines (red) with the IANIGLA outlines (blue). Simply changing the source will fix all the georeferencing issues. The IANIGLA outline dates are more recent (most in the last decade that I saw). Some UColorado dates are closer to 2000, but others are from the 60s. The outlines are always a large improvement.
<img width="708" alt="Screen Shot 2022-09-16 at 1 36 31 PM" src="https://user-images.githubusercontent.com/30648918/190700609-e5c89281-3d92-479f-b395-2519cecada9a.png">


The following regions still have some problems:
- [ ] 19-11: E Queen Maud Land 7A | 162 outlines | outlines date 1956
- [ ] 19-12: Amery Ice Shelf 7B | 1 outlines | outlines date 1956
- [ ] 19-13: Wilkes Land 7C | 73 outlines | outlines date 1956
- [ ] 19-14: Victoria Land 7D | 70 outlines | outlines date 2000
- [ ] 19-24: W Queen Maud Land 7K | 14 outlines | outlines date 1987

I have attached a word document that my students and I put together outlining some of the problems with imagery for each of these regions. We also included a document showing the problems in the regions we will fix if you are interested in seeing them.

Are others interested in taking on one of the subregions outlined above (11, 12, 13, 14, and 24)? @iamdonovan @bruceraup @eberthie @tbolch
My students and I may have capacity to do more, but we will start with 1, 2, 5, and 17.

[19-11- E Queen Maud Land 7A.docx](https://github.com/GLIMS-RGI/rgi7_scripts/files/9587195/19-11-.E.Queen.Maud.Land.7A.docx)
[19-12- Amery Ice Shelf 7B .docx](https://github.com/GLIMS-RGI/rgi7_scripts/files/9587198/19-12-.Amery.Ice.Shelf.7B.docx)
[19-13- Wilkes Land 7C .docx](https://github.com/GLIMS-RGI/rgi7_scripts/files/9587199/19-13-.Wilkes.Land.7C.docx)
[19-14- Victoria Land 7D.docx](https://github.com/GLIMS-RGI/rgi7_scripts/files/9587201/19-14-.Victoria.Land.7D.docx)
[19-24- W Queen Maud Land 7k .docx](https://github.com/GLIMS-RGI/rgi7_scripts/files/9587204/19-24-.W.Queen.Maud.Land.7k.docx)
[Examples of problems in regions we will fix.docx](https://github.com/GLIMS-RGI/rgi7_scripts/files/9587205/Examples.of.problems.in.regions.we.will.fix.docx)

**Comment by fmaussion** [comment]
Hi @willkochtitzky and team, thanks so much for looking into this. I am particularly thankful also for looking into other options in GLIMS:

- I will incorporate your suggestion for 19-03: Subantarctic (Atlantic). I understand then that your checked available GLIMS outlines for other subregions, and none would be of sufficient quality to avoid remapping. Correct?

**Comment by willkochtitzky** [comment]
@fmaussion, that is a really good point. I was working on 19-03, but my students did many of the other regions. I will check in with them to make sure that is the case and see if other GLIMS outlines might be suitable. Will circle back with you in the next couple days on that point.

**Comment by fmaussion** [comment]
Thanks! Here are the list of submissions available in the region (not in each subregion of course): 

https://nbviewer.org/urls/cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_scripts/workflow/RGI19.ipynb?flush_cache=true#List-of-submissions

Cook, Huber was proposed as "better" than RGI, but I found that the geometries and polygons are of poor quality (figures of 8, etc)

**Comment by eberthie** [comment]
Jérôme Lebreton, working with me on the Pléiades Glacier Observatory, is keen to contribute to the effort. Together with him we could work on **19-13: Wilkes Land**. I will put him in contact with Will for a few tips and some coordination.

**Comment by willkochtitzky** [comment]
> Thanks! Here are the list of submissions available in the region (not in each subregion of course):
> 
> https://nbviewer.org/urls/cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_scripts/workflow/RGI19.ipynb?flush_cache=true#List-of-submissions
> 
> Cook, Huber was proposed as "better" than RGI, but I found that the geometries and polygons are of poor quality (figures of 8, etc)

@fmaussion I unfortunately don't think any other regions have outlines that can be easily substituted. I checked the GLIMS outlines you linked above but 19-03 is the only region I am seeing with multiple outlines that fix the geolocation problem.

**Comment by fmaussion** [comment]
@willkochtitzky thanks for checking! This is very good to know. Then I'd say: please map what you can map and I'll take it ;-)

**Comment by willkochtitzky** [comment]
Roger that!

**Comment by iamdonovan** [comment]
I will have a look at some of the "unclaimed" regions above (11, 12, 14, 24) later tonight and see if I can help with mapping at least 1-2 of them.

**Comment by iamdonovan** [comment]
Okay, I've gone through region 19-24 (W Queen Maud Land 7K), and shifted/edited the outlines to match Landsat images from January-March 2000.

**Comment by fmaussion** [comment]
> Okay, I've gone through region 19-24 (W Queen Maud Land 7K), and shifted/edited the outlines to match Landsat images from January-March 2000.

Thanks so much!!! If you don't plan to do any other region, I think you can send the outlines to Bruce.

> I am not entirely convinced that they are all peripheral glaciers, rather than part of the ice sheet, but the outlines at least match up with the features they are meant to.

Yes - this is I think not for us to decide but for a dedicated working group in the future.

**Comment by iamdonovan** [comment]
> Yes - this is I think not for us to decide but for a dedicated working group in the future.

Agreed.

> If you don't plan to do any other region, I think you can send the outlines to Bruce.

I have downloaded images for region 19-14 (Victoria Land 7D), and will see what I can manage over the next week. From a brief look last night and this morning, it seems there are a lot of snowy rocks in this region. I will at least work on shifting/editing the current outlines, though.

**Comment by fmaussion** [comment]
Current Status:
- [ ] 19-13: Wilkes Land has been corrected / remapped by Jerome and Etienne, Bruce can ingest them in GLIMS
- [ ] 19-14 and 19-24 have been corrected / remapped by Bob and he sent them to Bruce already (email 06 October 2022)
- [ ] 19-05 19-01 19-17 19-02 are being worked on by Will and team.
- [ ] 19-11 19-12 are being worked on by Bob

**Comment by willkochtitzky** [comment]
I just sent this by email as well, but we just completed 19-05 19-01 19-17 19-02! They have been submitted to Bruce.

**Comment by iamdonovan** [comment]
emailed last night, but I have completed 19-11 and 19-12 now as well. The total number of glaciers came down by a lot in 19-11, as most of the outlines that I found appeared to be icebergs or snow-covered islands based on ca. 2000 Landsat and ASTER images.

**Comment by fmaussion** [comment]
@willkochtitzky thanks for finding out about **19-03: Subantarctic (Atlantic)**. I can see that the outlines from IANIGLA are much better where available, but one Island to the very west of the region has still only one submission available:

![image](https://user-images.githubusercontent.com/10050469/206903615-6a1eb01e-859a-4f09-b444-eb39d0afcd3f.png)

These outlines are much less problematic than the rest but are still a bit shifted:

![image](https://user-images.githubusercontent.com/10050469/206903694-df360cc7-5cfb-4293-a959-303c94b28b71.png)

I'll open a new issue for that - dont think it needs solving for RGI7

**Comment by iamdonovan** [comment]
Found a few more potential issues, in RGI 19-15 (Ross Ice Shelf 7E) and 19-16 (Marie Byrd Land 7F). Background is ESRI World Imagery:

![image](https://user-images.githubusercontent.com/5552374/207074919-7f3d926b-6cdd-410f-a48d-6e6d54aa2205.png)

![image](https://user-images.githubusercontent.com/5552374/207075068-5cd1efaf-103b-4a57-a79a-9c7601cd3d67.png)

I may have time to work on this before the end of the year if we think it's needed. Given that the issues seem similar enough to many of the other areas that we have corrected already, it feels like it makes sense to tackle now (but I'm also happy to be told otherwise).

**Comment by fmaussion** [comment]
@iamdonovan yes it does - end of the year is OK! Thanks so much for your help on this.

**Comment by willkochtitzky** [comment]
@fmaussion Thanks for pointing this out, I will fix this. Just running short on time the next few days here, but I can get it done by the end of the year.

**Comment by fmaussion** [comment]
@willkochtitzky happy for any help! Here is the current issue: https://github.com/GLIMS-RGI/rgi7_scripts/issues/66 

I would classify this as "medium" priority, but if it looks easy enough to do, yes please have a look at the two locations where RGI6 is still currently in use.

**Comment by iamdonovan** [comment]
![Screenshot from 2023-01-03 22-55-01](https://user-images.githubusercontent.com/5552374/210454922-d7867df3-1b0a-4139-ac0b-b24bf701e660.png)

I've made slow but steady progress on RGI19-15, which is a lot of complicated outlines. In the above screenshot, the purple represents the current (RGI6) outlines, and the red is the updated outlines I've digitized. The one thing that's missing now is the ice divides. I don't have a way to generate these nicely at the moment, so it feels like it makes the most sense to use the RGI6 divides as much as possible. Are there any thoughts/suggestions on this?

**Comment by fmaussion** [comment]
@iamdonovan thanks for your work on this. I'd say that having divides of medium quality is better than no divides, and I'd recommend to use the easiest path for you. RGI6 divides is fine!

**Comment by iamdonovan** [comment]
Thanks, @fmaussion. I've now finished outlining both 19-15 and 19-16, and only a week late. :)

On the note of divides, I can try to manually divide some of the larger "ice caps" using either the Landsat images (where the divides are sometimes very prominent) or the slope of the REMA DEM - I've attached an example for the Siple Island Ice Cap (RGI60-19.00417 and RGI60-19.00418). In RGI6, this is divided into 2 outlines:

![SipleOld](https://user-images.githubusercontent.com/5552374/211218438-272b522e-0549-4e73-9d5e-5cd11d350971.png)

For now, I can either leave this as-is (only 2 outlines), or I can further subdivide it using the topography:

![SipleNew](https://user-images.githubusercontent.com/5552374/211218485-8135a664-8fc4-45e5-ba93-6a90941b90a5.png)

On the one hand, this makes a lot more sense to me; on the other hand, we haven't really done this for any of the other regions, and I'm not sure I want to commit to doing this everywhere. Plus, because so many of these look like they are part of the ice sheets, they may eventually be dropped from the RGI altogether. So, should I just leave the divides as they were in RGI6, and wrap this up as "good enough for now"?

**Comment by fmaussion** [comment]
Thanks @iamdonovan !

> On the one hand, this makes a lot more sense to me

Yes

>  on the other hand, we haven't really done this for any of the other regions, and I'm not sure I want to commit to doing this everywhere.

I understand. Some regions have divides already, but these are the regions further away from the ice sheet. If you have done it for a few already, please submit the divided ones. Divided is always better than not.

> Plus, because so many of these look like they are part of the ice sheets, they may eventually be dropped from the RGI altogether.

Let's not put the cart before the horse ;-) This will be a long process...

> So, should I just leave the divides as they were in RGI6, and wrap this up as "good enough for now"?

Please use your best judgement and available time. Any improvement if good to take, but its also OK as is (since "as is" is already so much better than RGI6)

**Comment by iamdonovan** [comment]
> Let's not put the cart before the horse ;-) This will be a long process...

But that's my preferred MO. :)

> Please use your best judgement and available time. Any improvement if good to take, but its also OK as is (since "as is" is already so much better than RGI6)

I will finish up 19-16 by working on a few more divides (unlike the outlines, they are fairly quick). I'll send in what I have by the end of the night now.

**Comment by fmaussion** [comment]
RGI19 has improved by a great deal - thanks to all involved.
